#ifndef ARCH_ARM_HH
#define ARCH_ARM_HH

// For snapsnap, autogenerated file.
namespace ssnap {
    namespace arch {
        namespace arm {
            // ARM registers
            constexpr int invalid = 0;
            constexpr int apsr = 1;
            constexpr int apsr_nzcv = 2;
            constexpr int cpsr = 3;
            constexpr int fpexc = 4;
            constexpr int fpinst = 5;
            constexpr int fpscr = 6;
            constexpr int fpscr_nzcv = 7;
            constexpr int fpsid = 8;
            constexpr int itstate = 9;
            constexpr int lr = 10;
            constexpr int pc = 11;
            constexpr int sp = 12;
            constexpr int spsr = 13;
            constexpr int d0 = 14;
            constexpr int d1 = 15;
            constexpr int d2 = 16;
            constexpr int d3 = 17;
            constexpr int d4 = 18;
            constexpr int d5 = 19;
            constexpr int d6 = 20;
            constexpr int d7 = 21;
            constexpr int d8 = 22;
            constexpr int d9 = 23;
            constexpr int d10 = 24;
            constexpr int d11 = 25;
            constexpr int d12 = 26;
            constexpr int d13 = 27;
            constexpr int d14 = 28;
            constexpr int d15 = 29;
            constexpr int d16 = 30;
            constexpr int d17 = 31;
            constexpr int d18 = 32;
            constexpr int d19 = 33;
            constexpr int d20 = 34;
            constexpr int d21 = 35;
            constexpr int d22 = 36;
            constexpr int d23 = 37;
            constexpr int d24 = 38;
            constexpr int d25 = 39;
            constexpr int d26 = 40;
            constexpr int d27 = 41;
            constexpr int d28 = 42;
            constexpr int d29 = 43;
            constexpr int d30 = 44;
            constexpr int d31 = 45;
            constexpr int fpinst2 = 46;
            constexpr int mvfr0 = 47;
            constexpr int mvfr1 = 48;
            constexpr int mvfr2 = 49;
            constexpr int q0 = 50;
            constexpr int q1 = 51;
            constexpr int q2 = 52;
            constexpr int q3 = 53;
            constexpr int q4 = 54;
            constexpr int q5 = 55;
            constexpr int q6 = 56;
            constexpr int q7 = 57;
            constexpr int q8 = 58;
            constexpr int q9 = 59;
            constexpr int q10 = 60;
            constexpr int q11 = 61;
            constexpr int q12 = 62;
            constexpr int q13 = 63;
            constexpr int q14 = 64;
            constexpr int q15 = 65;
            constexpr int r0 = 66;
            constexpr int r1 = 67;
            constexpr int r2 = 68;
            constexpr int r3 = 69;
            constexpr int r4 = 70;
            constexpr int r5 = 71;
            constexpr int r6 = 72;
            constexpr int r7 = 73;
            constexpr int r8 = 74;
            constexpr int r9 = 75;
            constexpr int r10 = 76;
            constexpr int r11 = 77;
            constexpr int r12 = 78;
            constexpr int s0 = 79;
            constexpr int s1 = 80;
            constexpr int s2 = 81;
            constexpr int s3 = 82;
            constexpr int s4 = 83;
            constexpr int s5 = 84;
            constexpr int s6 = 85;
            constexpr int s7 = 86;
            constexpr int s8 = 87;
            constexpr int s9 = 88;
            constexpr int s10 = 89;
            constexpr int s11 = 90;
            constexpr int s12 = 91;
            constexpr int s13 = 92;
            constexpr int s14 = 93;
            constexpr int s15 = 94;
            constexpr int s16 = 95;
            constexpr int s17 = 96;
            constexpr int s18 = 97;
            constexpr int s19 = 98;
            constexpr int s20 = 99;
            constexpr int s21 = 100;
            constexpr int s22 = 101;
            constexpr int s23 = 102;
            constexpr int s24 = 103;
            constexpr int s25 = 104;
            constexpr int s26 = 105;
            constexpr int s27 = 106;
            constexpr int s28 = 107;
            constexpr int s29 = 108;
            constexpr int s30 = 109;
            constexpr int s31 = 110;
            constexpr int c1_c0_2 = 111;
            constexpr int c13_c0_2 = 112;
            constexpr int c13_c0_3 = 113;
            constexpr int ipsr = 114;
            constexpr int msp = 115;
            constexpr int psp = 116;
            constexpr int control = 117;
            constexpr int ending = 118;

            // alias registers
            constexpr int r13 = 12;
            constexpr int r14 = 10;
            constexpr int r15 = 11;
            constexpr int sb = 75;
            constexpr int sl = 76;
            constexpr int fp = 77;
            constexpr int ip = 78;
        }
    }
}

#endif
