#ifndef ARCH_M68K_HH
#define ARCH_M68K_HH

// For snapsnap, autogenerated file.
namespace ssnap {
    namespace arch {
        namespace m68k {
            // M68K registers
            constexpr int invalid = 0;
            constexpr int a0 = 1;
            constexpr int a1 = 2;
            constexpr int a2 = 3;
            constexpr int a3 = 4;
            constexpr int a4 = 5;
            constexpr int a5 = 6;
            constexpr int a6 = 7;
            constexpr int a7 = 8;
            constexpr int d0 = 9;
            constexpr int d1 = 10;
            constexpr int d2 = 11;
            constexpr int d3 = 12;
            constexpr int d4 = 13;
            constexpr int d5 = 14;
            constexpr int d6 = 15;
            constexpr int d7 = 16;
            constexpr int sr = 17;
            constexpr int pc = 18;
            constexpr int ending = 19;
        }
    }
}

#endif
