#ifndef ARCH_MIPS_HH
#define ARCH_MIPS_HH

// For snapsnap, autogenerated file.
namespace ssnap {
    namespace arch {
        namespace mips {
            // MIPS registers
            constexpr int invalid = 0;

            // General purpose registers
            constexpr int pc = 1;
            constexpr int r0 = 2;
            constexpr int r1 = 3;
            constexpr int r2 = 4;
            constexpr int r3 = 5;
            constexpr int r4 = 6;
            constexpr int r5 = 7;
            constexpr int r6 = 8;
            constexpr int r7 = 9;
            constexpr int r8 = 10;
            constexpr int r9 = 11;
            constexpr int r10 = 12;
            constexpr int r11 = 13;
            constexpr int r12 = 14;
            constexpr int r13 = 15;
            constexpr int r14 = 16;
            constexpr int r15 = 17;
            constexpr int r16 = 18;
            constexpr int r17 = 19;
            constexpr int r18 = 20;
            constexpr int r19 = 21;
            constexpr int r20 = 22;
            constexpr int r21 = 23;
            constexpr int r22 = 24;
            constexpr int r23 = 25;
            constexpr int r24 = 26;
            constexpr int r25 = 27;
            constexpr int r26 = 28;
            constexpr int r27 = 29;
            constexpr int r28 = 30;
            constexpr int r29 = 31;
            constexpr int r30 = 32;
            constexpr int r31 = 33;

            // DSP registers
            constexpr int dspccond = 34;
            constexpr int dspcarry = 35;
            constexpr int dspefi = 36;
            constexpr int dspoutflag = 37;
            constexpr int dspoutflag16_19 = 38;
            constexpr int dspoutflag20 = 39;
            constexpr int dspoutflag21 = 40;
            constexpr int dspoutflag22 = 41;
            constexpr int dspoutflag23 = 42;
            constexpr int dsppos = 43;
            constexpr int dspscount = 44;

            // ACC registers
            constexpr int ac0 = 45;
            constexpr int ac1 = 46;
            constexpr int ac2 = 47;
            constexpr int ac3 = 48;

            // COP registers
            constexpr int cc0 = 49;
            constexpr int cc1 = 50;
            constexpr int cc2 = 51;
            constexpr int cc3 = 52;
            constexpr int cc4 = 53;
            constexpr int cc5 = 54;
            constexpr int cc6 = 55;
            constexpr int cc7 = 56;

            // FPU registers
            constexpr int f0 = 57;
            constexpr int f1 = 58;
            constexpr int f2 = 59;
            constexpr int f3 = 60;
            constexpr int f4 = 61;
            constexpr int f5 = 62;
            constexpr int f6 = 63;
            constexpr int f7 = 64;
            constexpr int f8 = 65;
            constexpr int f9 = 66;
            constexpr int f10 = 67;
            constexpr int f11 = 68;
            constexpr int f12 = 69;
            constexpr int f13 = 70;
            constexpr int f14 = 71;
            constexpr int f15 = 72;
            constexpr int f16 = 73;
            constexpr int f17 = 74;
            constexpr int f18 = 75;
            constexpr int f19 = 76;
            constexpr int f20 = 77;
            constexpr int f21 = 78;
            constexpr int f22 = 79;
            constexpr int f23 = 80;
            constexpr int f24 = 81;
            constexpr int f25 = 82;
            constexpr int f26 = 83;
            constexpr int f27 = 84;
            constexpr int f28 = 85;
            constexpr int f29 = 86;
            constexpr int f30 = 87;
            constexpr int f31 = 88;
            constexpr int fcc0 = 89;
            constexpr int fcc1 = 90;
            constexpr int fcc2 = 91;
            constexpr int fcc3 = 92;
            constexpr int fcc4 = 93;
            constexpr int fcc5 = 94;
            constexpr int fcc6 = 95;
            constexpr int fcc7 = 96;

            // AFPR128
            constexpr int w0 = 97;
            constexpr int w1 = 98;
            constexpr int w2 = 99;
            constexpr int w3 = 100;
            constexpr int w4 = 101;
            constexpr int w5 = 102;
            constexpr int w6 = 103;
            constexpr int w7 = 104;
            constexpr int w8 = 105;
            constexpr int w9 = 106;
            constexpr int w10 = 107;
            constexpr int w11 = 108;
            constexpr int w12 = 109;
            constexpr int w13 = 110;
            constexpr int w14 = 111;
            constexpr int w15 = 112;
            constexpr int w16 = 113;
            constexpr int w17 = 114;
            constexpr int w18 = 115;
            constexpr int w19 = 116;
            constexpr int w20 = 117;
            constexpr int w21 = 118;
            constexpr int w22 = 119;
            constexpr int w23 = 120;
            constexpr int w24 = 121;
            constexpr int w25 = 122;
            constexpr int w26 = 123;
            constexpr int w27 = 124;
            constexpr int w28 = 125;
            constexpr int w29 = 126;
            constexpr int w30 = 127;
            constexpr int w31 = 128;
            constexpr int hi = 129;
            constexpr int lo = 130;
            constexpr int p0 = 131;
            constexpr int p1 = 132;
            constexpr int p2 = 133;
            constexpr int mpl0 = 134;
            constexpr int mpl1 = 135;
            constexpr int mpl2 = 136;
            constexpr int cp0_config3 = 137;
            constexpr int cp0_userlocal = 138;
            constexpr int ending = 139;
            constexpr int zero = 2;
            constexpr int at = 3;
            constexpr int v0 = 4;
            constexpr int v1 = 5;
            constexpr int a0 = 6;
            constexpr int a1 = 7;
            constexpr int a2 = 8;
            constexpr int a3 = 9;
            constexpr int t0 = 10;
            constexpr int t1 = 11;
            constexpr int t2 = 12;
            constexpr int t3 = 13;
            constexpr int t4 = 14;
            constexpr int t5 = 15;
            constexpr int t6 = 16;
            constexpr int t7 = 17;
            constexpr int s0 = 18;
            constexpr int s1 = 19;
            constexpr int s2 = 20;
            constexpr int s3 = 21;
            constexpr int s4 = 22;
            constexpr int s5 = 23;
            constexpr int s6 = 24;
            constexpr int s7 = 25;
            constexpr int t8 = 26;
            constexpr int t9 = 27;
            constexpr int k0 = 28;
            constexpr int k1 = 29;
            constexpr int gp = 30;
            constexpr int sp = 31;
            constexpr int fp = 32;
            constexpr int s8 = 32;
            constexpr int ra = 33;
            constexpr int hi0 = 45;
            constexpr int hi1 = 46;
            constexpr int hi2 = 47;
            constexpr int hi3 = 48;
            constexpr int lo0 = 45;
            constexpr int lo1 = 46;
            constexpr int lo2 = 47;
            constexpr int lo3 = 48;
        }
    }
}

#endif
