#ifndef ARCH_SPARC_HH
#define ARCH_SPARC_HH

// For snapsnap, autogenerated file.
namespace ssnap {
    namespace arch {
        namespace sparc {
            // SPARC registers
            constexpr int invalid = 0;
            constexpr int f0 = 1;
            constexpr int f1 = 2;
            constexpr int f2 = 3;
            constexpr int f3 = 4;
            constexpr int f4 = 5;
            constexpr int f5 = 6;
            constexpr int f6 = 7;
            constexpr int f7 = 8;
            constexpr int f8 = 9;
            constexpr int f9 = 10;
            constexpr int f10 = 11;
            constexpr int f11 = 12;
            constexpr int f12 = 13;
            constexpr int f13 = 14;
            constexpr int f14 = 15;
            constexpr int f15 = 16;
            constexpr int f16 = 17;
            constexpr int f17 = 18;
            constexpr int f18 = 19;
            constexpr int f19 = 20;
            constexpr int f20 = 21;
            constexpr int f21 = 22;
            constexpr int f22 = 23;
            constexpr int f23 = 24;
            constexpr int f24 = 25;
            constexpr int f25 = 26;
            constexpr int f26 = 27;
            constexpr int f27 = 28;
            constexpr int f28 = 29;
            constexpr int f29 = 30;
            constexpr int f30 = 31;
            constexpr int f31 = 32;
            constexpr int f32 = 33;
            constexpr int f34 = 34;
            constexpr int f36 = 35;
            constexpr int f38 = 36;
            constexpr int f40 = 37;
            constexpr int f42 = 38;
            constexpr int f44 = 39;
            constexpr int f46 = 40;
            constexpr int f48 = 41;
            constexpr int f50 = 42;
            constexpr int f52 = 43;
            constexpr int f54 = 44;
            constexpr int f56 = 45;
            constexpr int f58 = 46;
            constexpr int f60 = 47;
            constexpr int f62 = 48;
            constexpr int fcc0 = 49;
            constexpr int fcc1 = 50;
            constexpr int fcc2 = 51;
            constexpr int fcc3 = 52;
            constexpr int g0 = 53;
            constexpr int g1 = 54;
            constexpr int g2 = 55;
            constexpr int g3 = 56;
            constexpr int g4 = 57;
            constexpr int g5 = 58;
            constexpr int g6 = 59;
            constexpr int g7 = 60;
            constexpr int i0 = 61;
            constexpr int i1 = 62;
            constexpr int i2 = 63;
            constexpr int i3 = 64;
            constexpr int i4 = 65;
            constexpr int i5 = 66;
            constexpr int fp = 67;
            constexpr int i7 = 68;
            constexpr int icc = 69;
            constexpr int l0 = 70;
            constexpr int l1 = 71;
            constexpr int l2 = 72;
            constexpr int l3 = 73;
            constexpr int l4 = 74;
            constexpr int l5 = 75;
            constexpr int l6 = 76;
            constexpr int l7 = 77;
            constexpr int o0 = 78;
            constexpr int o1 = 79;
            constexpr int o2 = 80;
            constexpr int o3 = 81;
            constexpr int o4 = 82;
            constexpr int o5 = 83;
            constexpr int sp = 84;
            constexpr int o7 = 85;
            constexpr int y = 86;
            constexpr int xcc = 87;
            constexpr int pc = 88;
            constexpr int ending = 89;
            constexpr int o6 = 84;
            constexpr int i6 = 67;
        }
    }
}

#endif
