#ifndef UNICORN_INTERNAL_HH
#define UNICORN_INTERNAL_HH

// For snapsnap, autogenerated file.
namespace ssnap {
    namespace arch {
        namespace unicorn_internal {
            constexpr int API_MAJOR = 1;

            constexpr int API_MINOR = 0;
            constexpr int VERSION_MAJOR = 1;

            constexpr int VERSION_MINOR = 0;
            constexpr int VERSION_EXTRA = 2;
            constexpr int SECOND_SCALE = 1000000;
            constexpr int MILISECOND_SCALE = 1000;
            constexpr int ARCH_ARM = 1;
            constexpr int ARCH_ARM64 = 2;
            constexpr int ARCH_MIPS = 3;
            constexpr int ARCH_X86 = 4;
            constexpr int ARCH_PPC = 5;
            constexpr int ARCH_SPARC = 6;
            constexpr int ARCH_M68K = 7;
            constexpr int ARCH_MAX = 8;

            constexpr int MODE_LITTLE_ENDIAN = 0;
            constexpr int MODE_BIG_ENDIAN = 1073741824;

            constexpr int MODE_ARM = 0;
            constexpr int MODE_THUMB = 16;
            constexpr int MODE_MCLASS = 32;
            constexpr int MODE_V8 = 64;
            constexpr int MODE_ARM926 = 128;
            constexpr int MODE_ARM946 = 256;
            constexpr int MODE_ARM1176 = 512;
            constexpr int MODE_MICRO = 16;
            constexpr int MODE_MIPS3 = 32;
            constexpr int MODE_MIPS32R6 = 64;
            constexpr int MODE_MIPS32 = 4;
            constexpr int MODE_MIPS64 = 8;
            constexpr int MODE_16 = 2;
            constexpr int MODE_32 = 4;
            constexpr int MODE_64 = 8;
            constexpr int MODE_PPC32 = 4;
            constexpr int MODE_PPC64 = 8;
            constexpr int MODE_QPX = 16;
            constexpr int MODE_SPARC32 = 4;
            constexpr int MODE_SPARC64 = 8;
            constexpr int MODE_V9 = 16;

            constexpr int ERR_OK = 0;
            constexpr int ERR_NOMEM = 1;
            constexpr int ERR_ARCH = 2;
            constexpr int ERR_HANDLE = 3;
            constexpr int ERR_MODE = 4;
            constexpr int ERR_VERSION = 5;
            constexpr int ERR_READ_UNMAPPED = 6;
            constexpr int ERR_WRITE_UNMAPPED = 7;
            constexpr int ERR_FETCH_UNMAPPED = 8;
            constexpr int ERR_HOOK = 9;
            constexpr int ERR_INSN_INVALID = 10;
            constexpr int ERR_MAP = 11;
            constexpr int ERR_WRITE_PROT = 12;
            constexpr int ERR_READ_PROT = 13;
            constexpr int ERR_FETCH_PROT = 14;
            constexpr int ERR_ARG = 15;
            constexpr int ERR_READ_UNALIGNED = 16;
            constexpr int ERR_WRITE_UNALIGNED = 17;
            constexpr int ERR_FETCH_UNALIGNED = 18;
            constexpr int ERR_HOOK_EXIST = 19;
            constexpr int ERR_RESOURCE = 20;
            constexpr int ERR_EXCEPTION = 21;
            constexpr int MEM_READ = 16;
            constexpr int MEM_WRITE = 17;
            constexpr int MEM_FETCH = 18;
            constexpr int MEM_READ_UNMAPPED = 19;
            constexpr int MEM_WRITE_UNMAPPED = 20;
            constexpr int MEM_FETCH_UNMAPPED = 21;
            constexpr int MEM_WRITE_PROT = 22;
            constexpr int MEM_READ_PROT = 23;
            constexpr int MEM_FETCH_PROT = 24;
            constexpr int MEM_READ_AFTER = 25;
            constexpr int HOOK_INTR = 1;
            constexpr int HOOK_INSN = 2;
            constexpr int HOOK_CODE = 4;
            constexpr int HOOK_BLOCK = 8;
            constexpr int HOOK_MEM_READ_UNMAPPED = 16;
            constexpr int HOOK_MEM_WRITE_UNMAPPED = 32;
            constexpr int HOOK_MEM_FETCH_UNMAPPED = 64;
            constexpr int HOOK_MEM_READ_PROT = 128;
            constexpr int HOOK_MEM_WRITE_PROT = 256;
            constexpr int HOOK_MEM_FETCH_PROT = 512;
            constexpr int HOOK_MEM_READ = 1024;
            constexpr int HOOK_MEM_WRITE = 2048;
            constexpr int HOOK_MEM_FETCH = 4096;
            constexpr int HOOK_MEM_READ_AFTER = 8192;
            constexpr int HOOK_INSN_INVALID = 16384;
            constexpr int HOOK_MEM_UNMAPPED = 112;
            constexpr int HOOK_MEM_PROT = 896;
            constexpr int HOOK_MEM_READ_INVALID = 144;
            constexpr int HOOK_MEM_WRITE_INVALID = 288;
            constexpr int HOOK_MEM_FETCH_INVALID = 576;
            constexpr int HOOK_MEM_INVALID = 1008;
            constexpr int HOOK_MEM_VALID = 7168;
            constexpr int QUERY_MODE = 1;
            constexpr int QUERY_PAGE_SIZE = 2;
            constexpr int QUERY_ARCH = 3;
            constexpr int QUERY_TIMEOUT = 4;

            constexpr int PROT_NONE = 0;
            constexpr int PROT_READ = 1;
            constexpr int PROT_WRITE = 2;
            constexpr int PROT_EXEC = 4;
            constexpr int PROT_ALL = 7;
        }
    }
}

#endif
